### ISSUE TITLE
unsupported operand type(s) for +: 'int' and 'NoneType'

### ISSUE THREAD

**Issue by abayega** [scottgigante/picopore#10]
Hi,
running picopore gave me an error. Kindly advise;

$picopore --mode lossless -t 2 /media/abayega/Padlock_DT/reads/ecoli/C002_02_4_210616/reads

Performing lossless compression on 4564 files... 
Are you sure? (yes|no): yes
Unable to open file (Unknown flag for message)
...Unable to open file (File signature not found)
Unable to open file (File signature not found)
Unable to open file (File signature not found)
Unable to open file (File signature not found)
Unable to open file (File signature not found)
Unable to open file (File signature not found)
Unable to open file (File signature not found)
.Unable to open file (File signature not found)
..............Unable to open file (File signature not found)
Unable to open file (File signature not found)
Unable to open file (File signature not found)
Unable to open file (File signature not found)
Unable to open file (File signature not found)
Unable to open file (File signature not found)
Unable to open file (File signature not found)
Unable to open file (File signature not found)
Unable to open file (File signature not found)
Unable to open file (File signature not found)
......Unable to open file (Bad flag combination for message)
....Unable to open file (File signature not found)
Unable to open file (File signature not found)
Unable to open file (File signature not found)
Unable to open file (File signature not found)
Unable to open file (File signature not found)
Unable to open file (File signature not found)
Unable to open file (File signature not found)
Unable to open file (File signature not found)
Unable to open file (File signature not found)
Unable to open file (File signature not found)
..Unable to open file (File signature not found)
Unable to open file (File signature not found)
Unable to open file (File signature not found)
Unable to open file (File signature not found)
Unable to open file (File signature not found)
Unable to open file (File signature not found)
Unable to open file (Unknown flag for message)
Unable to open file (File signature not found)
......Unable to open file (File signature not found)
....Unable to open file (File signature not found)
Unable to open file (File signature not found)
.....Unable to open file (File signature not found)
Unable to open file (File signature not found)
Unable to open file (File signature not found)
Unable to open file (File signature not found)
...Traceback (most recent call last):
  File "/home/abayega/.local/bin/picopore", line 11, in <module>
    sys.exit(main())
  File "/home/abayega/.local/lib/python2.7/site-packages/picopore/__main__.py", line 101, in main
    exitcode = run(args.revert, args.mode, args.input, args.y, args.threads, args.group, args.prefix, args.fastq, args.summary, args.manual, args.print_every, args.skip_root)
  File "/home/abayega/.local/lib/python2.7/site-packages/picopore/__main__.py", line 45, in run
    postSize = multiprocessor.join()
  File "/home/abayega/.local/lib/python2.7/site-packages/picopore/multiprocess.py", line 43, in join
    return sum([r.get() for r in self.results])
TypeError: unsupported operand type(s) for +: 'int' and 'NoneType'

**Comment by abayega** [comment]
I got the same problem with python3.5 (though this may not yet be supported

....Traceback (most recent call last):
  File "/home/abayega/.local/bin/picopore", line 11, in <module>
    sys.exit(main())
  File "/home/abayega/.local/lib/python3.5/site-packages/picopore/__main__.py", line 101, in main
    exitcode = run(args.revert, args.mode, args.input, args.y, args.threads, args.group, args.prefix, args.fastq, args.summary, args.manual, args.print_every, args.skip_root)
  File "/home/abayega/.local/lib/python3.5/site-packages/picopore/__main__.py", line 45, in run
    postSize = multiprocessor.join()
  File "/home/abayega/.local/lib/python3.5/site-packages/picopore/multiprocess.py", line 43, in join
    return sum([r.get() for r in self.results])
TypeError: unsupported operand type(s) for +: 'int' and 'NoneType'

**Comment by scottgigante** [comment]
The terminal error you are seeing is itself rather easily fixed, but the large number of warnings printed prior to failure is a significant concern. I'd rather fix the cause rather than the symptom. May I ask what version of MinKNOW these reads were generated on? I haven't tested picopore on the latest update. 

As a side note, Python 3.5 should work just as well as 2.7 - the code is version agnostic.

**Comment by scottgigante** [comment]
Also, which version of picopore are you running? Would you mind cloning the latest commit, compiling and trying again?

**Comment by abayega** [comment]
Hi, am running version Picopore 1.1.5 installed last Thursday 24th via pip install picopore. I cant figure out which version of MinKnow we used to basecall the reads. I have attached a file from the supplied reads for your reference (extension changed from .fast5 to .txt).
[tiare_20160915_FNFAB29949_MN18767_sequencing_run_C002_05_6_82972_ch272_read171_strand.txt](https://github.com/scottgigante/picopore/files/1256972/tiare_20160915_FNFAB29949_MN18767_sequencing_run_C002_05_6_82972_ch272_read171_strand.txt)

**Comment by abayega** [comment]
The version was probably 1.0.5

**Comment by scottgigante** [comment]
I have run picopore with the settings and version you gave on the file you provided, and sadly(?) it runs perfectly. I've modified some logging settings to tell you which files are causing those warnings: could you please run the following:
```
git clone https://github.com/scottgigante/picopore.git
cd picopore
python setup.py install
picopore --mode lossless -t 2 /media/abayega/Padlock_DT/reads/ecoli/C002_02_4_210616/reads
```
It will produce the names of the files that are causing problems. If you could please send me one or two examples that would be great.

As a separate issue, since the reads were basecalled by a recent version of MinKNOW, lossless compression is unlikely to provide any improvement - please see the README for more information. However, I would still appreciate an example of the files that were causing this issue.

Thanks for reporting!

**Comment by scottgigante** [comment]
Alternatively, you should now be able to run `pip install --upgrade picopore` which will give you the new version 1.2.0, which should do the same thing.

**Comment by abayega** [comment]
Hi, Thanks for the advice. Here are some of the files causing that issue
[tiare_20160915_FNFAB29949_MN18767_sequencing_run_C002_05_6_82972_ch405_read326_strand.fast5.txt](https://github.com/scottgigante/picopore/files/1267393/tiare_20160915_FNFAB29949_MN18767_sequencing_run_C002_05_6_82972_ch405_read326_strand.fast5.txt)
[tiare_20160915_FNFAB29949_MN18767_sequencing_run_C002_05_6_82972_ch471_read93_strand.fast5.txt](https://github.com/scottgigante/picopore/files/1267395/tiare_20160915_FNFAB29949_MN18767_sequencing_run_C002_05_6_82972_ch471_read93_strand.fast5.txt)
[tiare_20160915_FNFAB29949_MN18767_sequencing_run_C002_05_6_82972_ch471_read708_strand.fast5.txt](https://github.com/scottgigante/picopore/files/1267394/tiare_20160915_FNFAB29949_MN18767_sequencing_run_C002_05_6_82972_ch471_read708_strand.fast5.txt)
[tiare_20160915_FNFAB29949_MN18767_sequencing_run_C002_05_6_82972_ch471_read734_strand.fast5.txt](https://github.com/scottgigante/picopore/files/1267396/tiare_20160915_FNFAB29949_MN18767_sequencing_run_C002_05_6_82972_ch471_read734_strand.fast5.txt)
[tiare_20160915_FNFAB29949_MN18767_sequencing_run_C002_05_6_82972_ch471_read746_strand1.fast5.txt](https://github.com/scottgigante/picopore/files/1267392/tiare_20160915_FNFAB29949_MN18767_sequencing_run_C002_05_6_82972_ch471_read746_strand1.fast5.txt)
[tiare_20160915_FNFAB29949_MN18767_sequencing_run_C002_05_6_82972_ch471_read755_strand.fast5.txt](https://github.com/scottgigante/picopore/files/1267400/tiare_20160915_FNFAB29949_MN18767_sequencing_run_C002_05_6_82972_ch471_read755_strand.fast5.txt)
[tiare_20160915_FNFAB29949_MN18767_sequencing_run_C002_05_6_82972_ch471_read788_strand.fast5.txt](https://github.com/scottgigante/picopore/files/1267399/tiare_20160915_FNFAB29949_MN18767_sequencing_run_C002_05_6_82972_ch471_read788_strand.fast5.txt)
[tiare_20160915_FNFAB29949_MN18767_sequencing_run_C002_05_6_82972_ch471_read810_strand.fast5.txt](https://github.com/scottgigante/picopore/files/1267397/tiare_20160915_FNFAB29949_MN18767_sequencing_run_C002_05_6_82972_ch471_read810_strand.fast5.txt)
[tiare_20160915_FNFAB29949_MN18767_sequencing_run_C002_05_6_82972_ch471_read861_strand.fast5.txt](https://github.com/scottgigante/picopore/files/1267398/tiare_20160915_FNFAB29949_MN18767_sequencing_run_C002_05_6_82972_ch471_read861_strand.fast5.txt)

**Comment by scottgigante** [comment]
I'm sorry to say that these files are broken. I cannot open them in HDFView or with hdf5-tools. To confirm that this isn't an artefact of the upload/download process, please run the same `h5ls` command as I did:
```
h5ls tiare_20160915_FNFAB29949_MN18767_sequencing_run_C002_05_6_82972_ch405_read326_strand.fast5
```
Here's the response:
```
tiare_20160915_FNFAB29949_MN18767_sequencing_run_C002_05_6_82972_ch405_read326_strand.fast5: unable to open file
```
I will mark this issue as closed for now. If you successfully open and view the contents of one of these files, please reopen it and we will find another way for me to look at your files.
