### ISSUE TITLE
Problem of picopore-rename

### ISSUE THREAD

**Issue by Bin-Ma** [scottgigante/picopore#13]
Hi @scottgigante. I want to rename the fast5 file for downstream analysis. After spliting the muti-fast5 files to the single files, the title of the fats5 files are performed as follow.
/                        Group
/Analyses                Group
/Analyses/Basecall_1D_000 Group
/Analyses/Basecall_1D_000/BaseCalled_template Group
/Analyses/Basecall_1D_000/BaseCalled_template/Fastq Dataset {SCALAR}
/Analyses/RawGenomeCorrected_000 Group
/Analyses/RawGenomeCorrected_000/BaseCalled_template Group
/Analyses/RawGenomeCorrected_000/BaseCalled_template/Alignment Group
/Analyses/RawGenomeCorrected_000/BaseCalled_template/Events Dataset {2839}
/Analyses/RawGenomeCorrected_001 Group
/Analyses/RawGenomeCorrected_001/BaseCalled_template Group
/Analyses/RawGenomeCorrected_001/BaseCalled_template/Alignment Group
/Analyses/RawGenomeCorrected_001/BaseCalled_template/Events Dataset {2839}
/Raw                     Group
/Raw/Reads               Group
/Raw/Reads/Read_6790     Group
/Raw/Reads/Read_6790/Signal Dataset {20479/Inf}
/UniqueGlobalKey         Group
/UniqueGlobalKey/channel_id Group
/UniqueGlobalKey/context_tags Group
/UniqueGlobalKey/tracking_id Group

I want to rename the "/Analyses/RawGenomeCorrected_000/BaseCalled_template/Events"  as "/Analyses/Basecall_1D_000/BaseCalled_template/Events" and I tried the command "picopore-rename ./aaf9a7ef-b910-4c72-b295-0f36ae8b152c.fast5 --from /Analyses/RawGenomeCorrected_000/BaseCalled_template/Events --to /Analyses/Basecall_1D_000/BaseCalled_template/Events.'' Unfortunately, It's not achieved well. Could you help me? Looking forward for your reply.

_Originally posted by @Bin-Ma in https://github.com/scottgigante/picopore/issues/9#issuecomment-1163116746_

**Comment by scottgigante** [comment]
Hi @Bin-Ma, unfortunately I am no longer actively maintaining picopore. Your best bet might be to look into using tools such as `h5py` or `pytables` to manually rename the group -- any HDF5 tools are capable of editing fast5 files.

**Comment by Bin-Ma** [comment]
Thanks for your reply and I will have a try of the HDF5 tools.
