### ISSUE TITLE
Python3 conflict (conda)

### ISSUE THREAD

**Issue by wdecoster** [scottgigante/picopore#2]
Hi,

Installation with conda is lovely, but on my newest server, I work using python 3 (3.6). Apparently, there is a conflict:

UnsatisfiableError: The following specifications were found to be in conflict:
  - picopore -> python 2.7*
  - python 3.6*

Is that something that could easily be solved?

Cheers,
Wouter

**Comment by druvus** [comment]
Hi @wdecoster ,
picopore doesn't support python 3 so I suggest you create a specific environment for python 2.7 with picopore. I assume that you have the channels set up according to Biocondas instructions (https://bioconda.github.io/). 

`conda create -n picopore python=2.7 picopore` 

You may now use the new environment by typing: 
`source activate picopore`

**Comment by wdecoster** [comment]
Thanks for the advice!

**Comment by scottgigante** [comment]
@druvus @wdecoster I've just upgraded picopore to support Python >=3.4. I've opened a PR on bioconda, or you can download and install from source in the meantime.
