### ISSUE TITLE
UnicodeDecodeError when install from Github

### ISSUE THREAD

**Issue by touala** [scottgigante/picopore#5]
Hi,
I'm trying to install picopore form github but `python3.5 setup.py install` crash with this error:

```
1.1.4
Traceback (most recent call last):
  File "setup.py", line 28, in <module>
    long_description=read('README.rst'),
  File "setup.py", line 19, in read
    return open(os.path.join(os.path.dirname(__file__), fname)).read()
  File "/python/3.5.0/lib/python3.5/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 4886: ordinal not in range(128)
```
Do you have some clue on how to fix that?

**Comment by touala** [comment]
I think I found why it crashes. The check mark character in README.rst cannot be decode with my configuration and it seems to be link to this python [issue](https://bugs.python.org/issue19846). I removed those character from the README file and it installed properly.

**Comment by scottgigante** [comment]
Thanks @touala for doing the hard work for me! This has now been resolved.
