### ISSUE TITLE
Is this py2, py3 or both?

### ISSUE THREAD

**Issue by tseemann** [scottgigante/picopore#7]
Docs don't specify which python you are using.

**Comment by tseemann** [comment]
Oh yes they do.  I need to RTFM more closely. Sorry :)

**Comment by scottgigante** [comment]
Easiest issue I've ever dealt with :)

**Comment by tseemann** [comment]
Although I failed to get it working on `python3`.  Errors with `cc -R` and Cython and `h5py`. I think it's a known bug, but it keeps cropping up (The `-R` should be `-Wl,rpath` or similar).

Only `python2` worked.

**Comment by scottgigante** [comment]
It works for me on Mac and CentOS. What OS are you running? I've had difficulty installing h5py on Windows unless I use anaconda.

**Comment by tseemann** [comment]
RHEL 7.x but I use Linuxbrew python2 and python3 - no system stuff.
MacOS brew installs it fine (with brewed python).  
Probably a linuxbrew bug i think (it's a fork of brew)

**Comment by scottgigante** [comment]
Hmm, that's frustrating. I'd say it's likely an h5py issue interacting with a linuxbrew bug given similar issues in Windows.
