### ISSUE TITLE
Unfriendly error when source folder doesn't exist

### ISSUE THREAD

**Issue by tseemann** [scottgigante/picopore#8]
I forgot to put "." before "/01/1D/fail"  and got this:

```
$ picopore --mode lossless --prefix PICOPORE --test -t 36 /01/1D/fail

No files found under []
No files found under []
Traceback (most recent call last):
  File "/home/linuxbrew/.linuxbrew/bin/picopore", line 11, in <module>
    load_entry_point('picopore==1.1.4', 'console_scripts', 'picopore')()
  File "/home/linuxbrew/.linuxbrew/Cellar/python/2.7.13/lib/python2.7/site-packages/picopore/__main__.py", line 93, in main
    exitcode = runTest(args)
  File "/home/linuxbrew/.linuxbrew/Cellar/python/2.7.13/lib/python2.7/site-packages/picopore/__main__.py", line 77, in runTest
    return exitcode
UnboundLocalError: local variable 'exitcode' referenced before assignment
```

**Comment by scottgigante** [comment]
Ooh, that's rather embarrassing. I'll have a look.

**Comment by scottgigante** [comment]
Looks like I may have already fixed this in the latest commit. Can you try installing from source and see if that works better? If so, all the more reason for me to push the latest update.

**Comment by tseemann** [comment]
Ok, installed HEAD.

Now it thinks the non-existent folder `./foo` is the parameter to `--print-every` ?


```
picopore --mode lossless -print-every 1 --threads 36 --test --prefix PICOPORE ./foo
usage: picopore [-h] [-v] --mode {lossless,deep-lossless,raw} [--revert]
                [--realtime | --test] [--fastq] [--summary] [--manual MANUAL]
                [--prefix PREFIX] [-y] [-t THREADS] [--skip-root]
                [--print-every PRINT_EVERY]
                [input [input ...]]
picopore: error: unrecognized arguments: -print-every ./foo
```

**Comment by tseemann** [comment]
Ok, with HEAD it does the nicer:
```
picopore --mode lossless --print-every 1 --threads 36 --test --prefix PICOPORE ./foo
No files found under []
No files found under []
```
But it's still a bit vague?

**Comment by tseemann** [comment]
```
Original size__: 13123318941
Compressed size: 13400299691
```
Made it worse on 14,000 files?

**Comment by scottgigante** [comment]
I've made the response friendlier - the `--test` finds the files first, then sends them to compression, so it was treating 'input' as an empty list.

Re: the size issue, I'm guessing these files were called recently - ONT have essentially adopted the `lossless` format in the last month or two. I'm yet to work out the cause of the 3% increase, there seems to be no difference in the spec between the old and new files. I might add this to the README, saying that lossless compression is functionally deprecated for new datasets.
