### ISSUE TITLE
Utility to change a group name

### ISSUE THREAD

**Issue by marcus1487** [scottgigante/picopore#9]
This utility may exist in another nanopore package, but I'm not aware of it. I was looking for a utility to change (or move) the name of a "basecalling" group and I'm not aware of one. picopore seems like it might be a good fit for this utiltiy (since it already deletes groups, so moving them would be somewhat related), but maybe it belongs in another package. Feel free to close this issue if you feel this is not in the scope of picopore.

**Comment by scottgigante** [comment]
Sorry for the slow response. Happy to throw it in, I was hoping to add at least one other "utility" that vaguely fits into the Picopore theme in the near future anyway. It will probably run with something like `picopore-rename --from /Analyses/Basecall_1D_000 --to /Analyses/Basecall_1D_albacore_v0 <fast5>`, unless you have a preference for something else. I'll let you know when I've got something for you to try.

**Comment by scottgigante** [comment]
@marcus1487 I've put together a `picopore-rename` utility - it is still very much experimental so please let me know if anything unexpected happens. It also required a (long-overdue) refactor of the code so if anything else breaks, same goes.

```
usage: picopore-rename [-h] -p PATTERN -r REPLACEMENT [-v] [-y] [-t THREADS]
                       [--prefix PREFIX] [--skip-root]
                       [--print-every PRINT_EVERY]
                       [input [input ...]]
```

**Comment by Bin-Ma** [comment]
Hi @scottgigante. I want to rename the fast5 file for downstream analysis. After spliting the muti-fast5 files to the single files, the title of the fats5 files are performed as follow.
/                        Group
/Analyses                Group
/Analyses/Basecall_1D_000 Group
/Analyses/Basecall_1D_000/BaseCalled_template Group
/Analyses/Basecall_1D_000/BaseCalled_template/Fastq Dataset {SCALAR}
/Analyses/RawGenomeCorrected_000 Group
/Analyses/RawGenomeCorrected_000/BaseCalled_template Group
/Analyses/RawGenomeCorrected_000/BaseCalled_template/Alignment Group
/Analyses/RawGenomeCorrected_000/BaseCalled_template/Events Dataset {2839}
/Analyses/RawGenomeCorrected_001 Group
/Analyses/RawGenomeCorrected_001/BaseCalled_template Group
/Analyses/RawGenomeCorrected_001/BaseCalled_template/Alignment Group
/Analyses/RawGenomeCorrected_001/BaseCalled_template/Events Dataset {2839}
/Raw                     Group
/Raw/Reads               Group
/Raw/Reads/Read_6790     Group
/Raw/Reads/Read_6790/Signal Dataset {20479/Inf}
/UniqueGlobalKey         Group
/UniqueGlobalKey/channel_id Group
/UniqueGlobalKey/context_tags Group
/UniqueGlobalKey/tracking_id Group

I want to rename the "/Analyses/RawGenomeCorrected_000/BaseCalled_template/Events"  as "/Analyses/Basecall_1D_000/BaseCalled_template/Events" and I tried the command "picopore-rename ./aaf9a7ef-b910-4c72-b295-0f36ae8b152c.fast5 --from /Analyses/RawGenomeCorrected_000/BaseCalled_template/Events --to /Analyses/Basecall_1D_000/BaseCalled_template/Events.'' Unfortunately, It's not achieved well. Could you help me? Looking forward for your reply.
